base_url: "https://app.tst.gap-check.wageindicator.org/login"
Admin:
  username: "gAAAAAAAAAAARBqIVcKC4ulugk-f_5PzphJ_IQC6DI5TmgFFXpmR18dUZukWfZGY4vagA0Jv-CaEYwwCCD9nC7jx9VpFs3sg7mjOK9I5v8X2eFZiyGb9fs0"
  password: "gAAAAAAAAAAABaUeKDYUDHg0XODnlawTN-_jI50YaQbjRsxIeaI5Tp9UnoI1txSPUIbrEXMhqdZ2N2-PANh2uZw1Ux6MVhVt3g"
